Add initial implementation for message-observer
ConsenSys/gpact pull request #71
Opened 2021-12-15 06:27 UTC by ermyas

This PR adds an initial implementation of a Relayer's [message-observer component](https://github.com/ConsenSys/gpact/blob/main/doc/relayer-design.md). This component is responsible for listening to configured events, transforming them into the common message format and then enqueueing the messages onto a queue for further processing by other Relayer components.

2021-12-15 07:00 UTC, drinkcoffee requested changes
I have put some comments in for changes.

2021-12-15 07:04 UTC, ermyas commented on messaging/relayer/internal/msgobserver/eth/soliditywrappers/sfc/simple_crosschain_control.go
> +// Code generated - DO NOT EDIT.
good point

2021-12-15 10:21 UTC, ermyas commented on messaging/relayer/internal/msgobserver/eth/soliditywrappers/sfc/simple_crosschain_control.go
> +// Code generated - DO NOT EDIT.
moved the `soliditywrappers` folder outside of the message observer

2021-12-15 10:22 UTC, ermyas commented on messaging/relayer/internal/msgobserver/eth/utils.go
> +	"crypto/rand"
updated to use our prng

2021-12-15 22:23 UTC, wcgcyx approved these changes

2021-12-16 00:34 UTC, drinkcoffee approved these changes

2021-12-16 00:38 UTC, merged